# Generated by Django 5.1.15 on 2026-05-21 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#0B7A4B",
                        help_text="Hex colour used for the category badge, e.g. #0B7A4B",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Category",
                "verbose_name_plural": "Article Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=290, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short summary shown on listing cards (max 400 chars).",
                        max_length=400,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full article body. HTML tags are rendered — wrap paragraphs in <p> tags."
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        help_text="Recommended size: 1200×630 px (16:9).",
                        null=True,
                        upload_to="articles/images/",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Optional YouTube / Vimeo embed URL."
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank to auto-set when you first publish.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="articles.articlecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
