from django.urls import path

from .views import (
    admin_dashboard,
    admin_user_add,
    admin_user_delete,
    admin_user_detail,
    admin_user_edit,
    admin_user_reset_password,
    admin_users,
    dentist_appointment_detail,
    dentist_articles_page,
    dentist_ask_doctor_page,
    dentist_dashboard,
    dentist_followup_edit,
    dentist_followup_status,
    dentist_followups_page,
    dentist_my_appointments,
    dentist_my_patients,
    dentist_notifications_page,
    dentist_patient_detail,
    patient_appointments_page,
    patient_book_page,
    patient_cancel_appointment,
    patient_dashboard,
    patient_invoices_page,
    patient_notifications_page,
    patient_profile_page,
    patient_treatments_page,
    receptionist_appointments_page,
    receptionist_dashboard,
    receptionist_notifications_page,
    receptionist_profile_page,
    role_dashboard_redirect,
    update_appointment_status,
)

app_name = "dashboard"

urlpatterns = [
    path("", role_dashboard_redirect, name="redirect"),
    path("admin/", admin_dashboard, name="admin"),
    path("admin/users/", admin_users, name="admin_users"),
    path("admin/users/add/", admin_user_add, name="admin_user_add"),
    path("admin/users/<int:pk>/", admin_user_detail, name="admin_user_detail"),
    path("admin/users/<int:pk>/edit/", admin_user_edit, name="admin_user_edit"),
    path("admin/users/<int:pk>/reset-password/", admin_user_reset_password, name="admin_user_reset_password"),
    path("admin/users/<int:pk>/delete/", admin_user_delete, name="admin_user_delete"),
    path("dentist/", dentist_dashboard, name="dentist"),
    path("dentist/my-appointments/", dentist_my_appointments, name="dentist_my_appointments"),
    path("dentist/my-appointments/<int:pk>/", dentist_appointment_detail, name="dentist_appointment_detail"),
    path("dentist/my-patients/", dentist_my_patients, name="dentist_my_patients"),
    path("dentist/my-patients/<int:pk>/", dentist_patient_detail, name="dentist_patient_detail"),
    path("dentist/ask-doctor/", dentist_ask_doctor_page, name="dentist_ask_doctor"),
    path("dentist/articles/", dentist_articles_page, name="dentist_articles"),
    path("dentist/notifications/", dentist_notifications_page, name="dentist_notifications"),
    path("dentist/follow-ups/", dentist_followups_page, name="dentist_followups"),
    path("dentist/follow-ups/<int:pk>/edit/", dentist_followup_edit, name="dentist_followup_edit"),
    path("dentist/follow-ups/<int:pk>/status/<str:status>/", dentist_followup_status, name="dentist_followup_status"),
    path("dentist/appointments/<int:pk>/<str:status>/", update_appointment_status, name="dentist_appointment_status"),
    path("receptionist/", receptionist_dashboard, name="receptionist"),
    path("receptionist/appointments/", receptionist_appointments_page, name="receptionist_appointments"),
    path("receptionist/notifications/", receptionist_notifications_page, name="receptionist_notifications"),
    path("receptionist/profile/", receptionist_profile_page, name="receptionist_profile"),
    path("patient/", patient_dashboard, name="patient"),
    path("patient/appointments/<int:pk>/cancel/", patient_cancel_appointment, name="patient_cancel_appointment"),
    path("patient/appointments/", patient_appointments_page, name="patient_appointments"),
    path("patient/book/", patient_book_page, name="patient_book"),
    path("patient/notifications/", patient_notifications_page, name="patient_notifications"),
    path("patient/treatments/", patient_treatments_page, name="patient_treatments"),
    path("patient/invoices/", patient_invoices_page, name="patient_invoices"),
    path("patient/profile/", patient_profile_page, name="patient_profile"),
]
