from django.urls import path

from .views import (
    admin_dashboard,
    admin_user_add,
    admin_user_delete,
    admin_user_detail,
    admin_user_edit,
    admin_user_reset_password,
    admin_users,
    dentist_dashboard,
    patient_appointments_page,
    patient_book_page,
    patient_cancel_appointment,
    patient_dashboard,
    patient_invoices_page,
    patient_notifications_page,
    patient_profile_page,
    patient_treatments_page,
    receptionist_appointments_page,
    receptionist_dashboard,
    receptionist_notifications_page,
    receptionist_profile_page,
    role_dashboard_redirect,
    update_appointment_status,
)

app_name = "dashboard"

urlpatterns = [
    path("", role_dashboard_redirect, name="redirect"),
    path("admin/", admin_dashboard, name="admin"),
    path("admin/users/", admin_users, name="admin_users"),
    path("admin/users/add/", admin_user_add, name="admin_user_add"),
    path("admin/users/<int:pk>/", admin_user_detail, name="admin_user_detail"),
    path("admin/users/<int:pk>/edit/", admin_user_edit, name="admin_user_edit"),
    path("admin/users/<int:pk>/reset-password/", admin_user_reset_password, name="admin_user_reset_password"),
    path("admin/users/<int:pk>/delete/", admin_user_delete, name="admin_user_delete"),
    path("dentist/", dentist_dashboard, name="dentist"),
    path("dentist/appointments/<int:pk>/<str:status>/", update_appointment_status, name="dentist_appointment_status"),
    path("receptionist/", receptionist_dashboard, name="receptionist"),
    path("receptionist/appointments/", receptionist_appointments_page, name="receptionist_appointments"),
    path("receptionist/notifications/", receptionist_notifications_page, name="receptionist_notifications"),
    path("receptionist/profile/", receptionist_profile_page, name="receptionist_profile"),
    path("patient/", patient_dashboard, name="patient"),
    path("patient/appointments/<int:pk>/cancel/", patient_cancel_appointment, name="patient_cancel_appointment"),
    path("patient/appointments/", patient_appointments_page, name="patient_appointments"),
    path("patient/book/", patient_book_page, name="patient_book"),
    path("patient/notifications/", patient_notifications_page, name="patient_notifications"),
    path("patient/treatments/", patient_treatments_page, name="patient_treatments"),
    path("patient/invoices/", patient_invoices_page, name="patient_invoices"),
    path("patient/profile/", patient_profile_page, name="patient_profile"),
]
