# Generated by Django 5.1.15 on 2026-05-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_dentalservice_image_descriptions_timestamps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dentalservice",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
    ]
