# Generated by Django 5.1.15 on 2026-05-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_alter_dentalservice_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dentalservice",
            name="base_price",
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="services/")),
                ("alt_text", models.CharField(blank=True, max_length=160)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="services.dentalservice",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at", "pk"],
            },
        ),
    ]
