# Generated by Django 5.1.15 on 2026-05-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clinic_name",
                    models.CharField(default="DentalCare Clinic", max_length=200),
                ),
                ("clinic_email", models.EmailField(blank=True, max_length=254)),
                ("clinic_phone", models.CharField(blank=True, max_length=30)),
                ("clinic_address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.FileField(blank=True, null=True, upload_to="clinic/logo/"),
                ),
                ("opening_time", models.TimeField(default="08:00")),
                ("closing_time", models.TimeField(default="17:00")),
                ("appointment_duration", models.PositiveIntegerField(default=30)),
                ("allow_online_booking", models.BooleanField(default=True)),
                ("auto_approve_appointments", models.BooleanField(default=False)),
                ("enable_email_notifications", models.BooleanField(default=True)),
                ("enable_sms_notifications", models.BooleanField(default=False)),
                ("appointment_reminder_time", models.PositiveIntegerField(default=24)),
                ("admin_email", models.EmailField(blank=True, max_length=254)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("invoice_prefix", models.CharField(default="INV", max_length=20)),
                (
                    "payment_methods",
                    models.CharField(blank=True, default="Cash,Card", max_length=200),
                ),
                ("require_strong_password", models.BooleanField(default=True)),
                ("session_timeout", models.PositiveIntegerField(default=30)),
                ("enable_two_factor_auth", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Clinic Setting",
            },
        ),
    ]
