# Generated by Django 5.1.15 on 2026-05-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
        ("dentists", "0003_dentistprofile_appointment_duration_and_more"),
        ("patients", "0002_patientprofile_profile_image"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_dentist_appointment_slot",
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "approved", "completed"])
                ),
                fields=("dentist", "appointment_date", "appointment_time"),
                name="unique_dentist_appointment_slot",
            ),
        ),
    ]
