# Generated by Django 5.1.15 on 2026-05-12 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "appointments",
            "0002_remove_appointment_unique_dentist_appointment_slot_and_more",
        ),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="estimated_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="estimated_duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="services.dentalservice",
            ),
        ),
    ]
