# Generated by Django 5.1.15 on 2026-05-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dentists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dentistprofile",
            name="available_days",
            field=models.CharField(
                default="Monday,Tuesday,Wednesday,Thursday,Friday",
                help_text="Comma-separated days, for example: Monday,Tuesday,Wednesday",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="dentistprofile",
            name="available_from",
            field=models.TimeField(default="09:00"),
        ),
        migrations.AlterField(
            model_name="dentistprofile",
            name="available_to",
            field=models.TimeField(default="17:00"),
        ),
        migrations.AlterField(
            model_name="dentistprofile",
            name="license_number",
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name="dentistprofile",
            name="specialization",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
