# Generated by Django 5.1.15 on 2026-05-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dentists", "0002_alter_dentistprofile_available_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dentistprofile",
            name="appointment_duration",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="dentistprofile",
            name="break_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dentistprofile",
            name="break_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dentistprofile",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dentistprofile",
            name="max_patients_per_day",
            field=models.PositiveIntegerField(default=12),
        ),
    ]
