# Generated by Django 5.1.15 on 2026-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_patientprofile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="preferred_language",
            field=models.CharField(
                choices=[("rw", "Kinyarwanda"), ("en", "English")],
                default="rw",
                max_length=2,
            ),
        ),
    ]
