# Generated by Django 5.1.15 on 2026-05-27 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0003_add_service_fields"),
        ("notifications", "0002_notificationlog"),
        ("patients", "0003_patientprofile_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="fallback_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fallback_for",
                to="notifications.notificationlog",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="fallback_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="parent_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fallback_attempts",
                to="notifications.notificationlog",
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("undelivered", "Undelivered"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["provider_sid"], name="notificatio_provide_7eaf94_idx"
            ),
        ),
    ]
